version: "3.2"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: ice-project-elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    container_name: ice-project-kibana
    restart: always
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch